import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
//Components
import Main from "@/components/Layout/Main";
import Grid from "@/components/Layout/Grid";
import Button from "@/components/UI/Button";
import SearchForm from "@/components/UI/SearchForm";
import SubjectTitle from "@/components/UI/SubjectTitle";
import ArticleList from "@/components/UI/ArticleList";

const Gallery = () => {
  const router = useRouter();
  const navigateToWrite = () => {
    router.push("/gallery/write");
  };
  const [articles, setArticles] = useState([]);

  const fetchArticles = async () => {
    try {
      const res = await fetch("/api/gallery/article");
      const data = await res.json();
      setArticles(data);
    } catch (error) {
      console.log(error, "게시글을 불러오기 에러");
    }
  };

  useEffect(() => {
    fetchArticles();
  }, []);

  return (
    <>
      <Head>
        <title>자유게시판</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid $column="1fr" $place="center">
        <Main>
          <Grid $column="1fr auto" $place="end">
            <SearchForm />
            <Button onClick={navigateToWrite}>글쓰기</Button>
          </Grid>
          <Grid $column="1fr">
            <SubjectTitle title="자유게시판" text="자유롭게 이야기를 해요." />
            {articles.length === 0 ? (
              <p>전체 게시물 로딩 중 ...</p>
            ) : (
              <ArticleList articles={articles} />
            )}
          </Grid>
        </Main>
      </Grid>
    </>
  );
};

export default Gallery;
