import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
//Components
import Layout from "@/components/Layout/Layout";
import Grid from "@/components/Layout/Grid";
import Button from "@/components/UI/Button";
import SearchForm from "@/components/UI/SearchForm";
import SubjectTitle from "@/components/UI/SubjectTitle";
import ArticleList from "@/components/UI/ArticleList";

const gallery = () => {
  const router = useRouter();
  const navigateToWrite = () => {
    router.push("/write");
  };

  const dummyList = [
    {
      id: 1,
      title: "제목1",
      text: "제목1",
      date: new Date().toLocaleDateString(),
    },
    {
      id: 2,
      title: "제목1",
      text: "제목2",
      date: new Date().toLocaleDateString(),
    },
    {
      id: 3,
      title: "제목1",
      text: "제목3",
      date: new Date().toLocaleDateString(),
    },
    {
      id: 4,
      title: "제목1",
      text: "제목4",
      date: new Date().toLocaleDateString(),
    },
  ];

  return (
    <>
      <Head>
        <title>자유게시판</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Grid column="1fr auto" place="end">
          <SearchForm />
          <Button onClick={navigateToWrite}>글쓰기</Button>
        </Grid>
        <Grid column={"1fr"}>
          <SubjectTitle
            title="자유게시판"
            text="자유롭게 작업 이야기를 해요."
          />
          <ArticleList articleListData={dummyList} />
        </Grid>
      </Layout>
    </>
  );
};

export default gallery;
