import React, { useState, useContext } from "react";
import Head from "next/head";
import { ColorPicker, useColor } from "react-color-palette";
import "react-color-palette/css";
//Utils
import { renderPlayground } from "@/util/getRenderPlayground";
//Contexts
import { MenuContext } from "@/contexts/MenuContext";
//Components
import Main from "@/components/Layout/Main";
import Grid from "@/components/Layout/Grid";
import SideNav from "@/components/Layout/SideNav";
import SubjectTitle from "@/components/UI/SubjectTitle";
import Card from "@/components/UI/Card";
import CardHead from "@/components/UI/CardHead";

const Showcase = () => {
  const [color, setColor] = useColor("#982c64");
  const [secondColor, setSecondColor] = useColor("#5628fa");
  const { menuState } = useContext(MenuContext);

  return (
    <>
      <Head>
        <title>Yum Ui Components Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid $column="1fr 3fr" $place="stretch">
        <SideNav />
        <Main>
          <Grid $column="repeat(2, 1fr)">
            <Card>
              <CardHead>1. 메인칼라를 고르세요</CardHead>
              <ColorPicker color={color} onChange={setColor} />
            </Card>
            <Card>
              <CardHead>2. 서브칼라를 고르세요</CardHead>
              <ColorPicker color={secondColor} onChange={setSecondColor} />
            </Card>
          </Grid>
          <SubjectTitle title={menuState.toUpperCase()} />
          <Grid $column="repeat(2, 1fr)">
            {renderPlayground({
              menuState,
              colorHex: color.hex,
              secondColorHex: secondColor.hex,
            })}
          </Grid>
        </Main>
      </Grid>
    </>
  );
};

export default Showcase;
