import React, { useState } from "react";
import dynamic from "next/dynamic";
import Head from "next/head";
//Components
import Layout from "@/components/Layout/Layout";
import Grid from "@/components/Layout/Grid";
import Input from "@/components/UI/Input";

const Editor = dynamic(() => import("@/components/UI/Editor"), {
  ssr: false,
  loading: () => <p>로딩 중</p>,
});

const Write = () => {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");

  const onChangeTitle = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTitle(e.target.value);
  };

  const onChangeContent = (content: string) => {
    setContent(content);
  };
  return (
    <>
      <Head>
        <title>글쓰기</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Grid column={"1fr"}>
          {title}
          {content}
          <Input
            placeholder="제목을 적어주세요."
            value={title}
            onChange={onChangeTitle}
          />
          <Editor onChange={onChangeContent} />
        </Grid>
      </Layout>
    </>
  );
};

export default Write;
