import React, { useState } from "react";
import Head from "next/head";
//Components
import Layout from "@/components/Layout/Layout";
import Grid from "@/components/Layout/Grid";
import Editor from "@/components/UI/Editor";
import Input from "@/components/UI/Input";

const write = () => {
  const [title, setTitle] = useState("");
  const [value, setValue] = useState("");
  return (
    <>
      <Head>
        <title>글쓰기</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Grid column={"1fr"}>
          <Input placeholder="제목을 적어주세요." />
          <Editor value={value} onChange={setValue} />
        </Grid>
      </Layout>
    </>
  );
};

export default write;
